# Generated by Django 5.2.12 on 2026-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=255)),
                ('operator_name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(choices=[('LASER', 'Laser'), ('UV', 'UV')], max_length=20)),
                ('job_date', models.DateField()),
                ('job_type', models.CharField(choices=[('CUT', 'CUT'), ('ENGRAVE', 'ENGRAVE'), ('COMBO', 'COMBO'), ('PRINT', 'PRINT')], max_length=50)),
                ('material', models.CharField(max_length=255)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('preset', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_seconds', models.PositiveIntegerField(default=0)),
                ('downtime_seconds', models.PositiveIntegerField(default=0)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('qty_pcs', models.PositiveIntegerField(default=0)),
                ('good_qty', models.PositiveIntegerField(default=0)),
                ('reject_qty', models.PositiveIntegerField(default=0)),
                ('reject_reasons', models.JSONField(blank=True, default=list)),
                ('qc_status', models.CharField(choices=[('OK', 'OK'), ('REWORK', 'REWORK'), ('HOLD', 'HOLD')], default='OK', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('price_mode', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-job_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('LASER', 'Laser'), ('UV', 'UV')], max_length=20)),
                ('job_type', models.CharField(choices=[('CUT', 'CUT'), ('ENGRAVE', 'ENGRAVE'), ('COMBO', 'COMBO'), ('PRINT', 'PRINT')], max_length=50)),
                ('price_mode', models.CharField(blank=True, choices=[('per_minute', 'Per Menit'), ('per_piece', 'Per Pcs'), ('per_job', 'Per Job')], max_length=20, null=True)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
